### ISSUE TITLE
The scroll doesn't work on a mobile phone

### ISSUE THREAD

**Issue by yoloSwagSEO** [VanOns/laraberg#90]
**Describe the bug**

**To Reproduce**
When I'm on my cell phone.
Can't scroll to the page if a laraberg instance is present.
We can reproduce the bug with google chrome responsive mode.

**Comment by Piastra91** [comment]
up!

**Comment by bagusindrayana** [comment]
226/5000
I also have the same thing where the block editor isn't scrollable within an element unless you have the parent element that has a fixed height and creates `overflow: scroll` attribute on the parent element
example
```html
<div class="form-group" style="height:400px;overflow:scroll;">
 <textarea id="content" name="content" hidden></textarea>
</div>
```

or you set your height directly when you init Laraberg
```javascript
Laraberg.init('content',{height:'80vh'});
```

if you want make more responsive you need some custom css and edit elemen with id `laraberg__editor` or class `laraberg__editor gutenberg__editor block-editor__container wp-embed-responsive fixed-height`
something like this
```css
/* for mobile */
#laraberg__editor {
    height: 60vh !important;
}

/* for desktop */
@media only screen and (min-width: 768px) {
    #laraberg__editor {
        height: auto !important;
    }
}
```
